name: Check that everything builds

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: latest

      - name: Npm install
        run: npm ci

      - name: Npm build
        run: npm run build

      - name: Run tests
        run: npm run test
